### ISSUE TITLE
build 没有上传？？？？？？

### ISSUE THREAD

**Issue by yuanmingqing** [BeanWei/Dailyfresh-B2C#2]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'D:\Front\build\dev-server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-node-mall@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-node-mall@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\PC-01\AppData\Roaming\npm-cache\_logs\2019-09-22T15_27_56_288Z-debug.log

**Comment by xiaoheishan** [comment]
还真没有，研究了半天😡😡

**Comment by buildding** [comment]
服了你了，要开源就全开，少这少那的，专折磨人！
